name: alexruizart
favicon: null
layout_spectrum: 0.23069
typography_spectrum: 0.6957
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0d14'
    - '#4f5f5f'
    - '#303a3c'
    - '#9ca69b'
    - '#c7c9bb'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
