name: alexruizart
favicon: null
layout_spectrum: 0.02423904277384281
typography_spectrum: 0.026083675678819418
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.516735072247684
  lightness: 0.0982163199223578
  saturation: 0.6543891273904592
  rhythmicContrast: 0.6671222622971982
purpose: []
